### ISSUE TITLE
USB port lacks 5V power; SOM does not generate 5V power! re-arrange the power supply chip and let the PHY generate one of the voltages internally

### ISSUE THREAD

**Issue by gyorka** [elhep/SPEC_A7_Management#10]

**Comment by gyorka** [comment]
USB as is is configured for DEVICE mode of operation (5k1 resistors on CC pins), and 5V should be provided from the host
On SoM there is voltage divider on that pin to detect it.
USB port in this form is inteded to be used as SoM firmware update port, nothing else
for more convinient firmware development, SD card connector is provided, and we can use ethernet and scp for smaller files

**Comment by gkasprow** [comment]
This is USB Host. Please add jumper that let the user to switch roles.
We need USB host to talk to FTDI on lower board to debug FPGA design remotely.
