### ISSUE TITLE
add 33Ohm series termination resistors at the RGMII output lines that go to the FPGA

### ISSUE THREAD

**Issue by gyorka** [elhep/SPEC_A7_Management#6]

**Comment by gyorka** [comment]
at spec_a7 fpga_34.schdoc there are 33R resistors at RGMII TX lines, should we add 33R resistors at RX lines here? or its already good as it is?
![image](https://github.com/elhep/SPEC_A7_Management/assets/89603415/6b62965b-4dcb-44eb-bf81-6b8896eaebf0)

**Comment by gkasprow** [comment]
Oh, the resistor on SPEC side are on wrong lines, FPGA Tx means input; Add them on Tx lines on your side

**Comment by gyorka** [comment]
so I should also connect TX to RX port and vice versa?

**Comment by gkasprow** [comment]
No, follow Ethernet rules; Rx connects with Rx, Tx with Tx;
use source ermination on your output signals

**Comment by gyorka** [comment]
![image](https://github.com/elhep/SPEC_A7_Management/assets/89603415/4bcb2809-81fa-473a-9ba3-e2fbbde5bbf3)
done
