### ISSUE TITLE
pls add voltage detection circuit that will report loss of one of redundant supplies ; do NOT connect P5V0 rail to this connector!

### ISSUE THREAD

**Issue by gyorka** [elhep/SPEC_A7_Management#7]

**Comment by gyorka** [comment]
we have no redundant power supply - all we have is a single 12V source plus a single 3.3V source

what good would detection of 12V supply loss would do if our lights went off?

**Comment by gkasprow** [comment]
We do have redundant power supply
![obraz](https://github.com/elhep/SPEC_A7_Management/assets/4325054/6b3793e3-b32e-440f-8884-d5795213d25d)

**Comment by gyorka** [comment]
as already stated: we don't have any redundant power supply within spec_a7_managment board - all we have is single 12V supply and single 3.3V supply

**Comment by gkasprow** [comment]
Just implement it. We do have redundant power board with 2 IEC power entries.

**Comment by gkasprow** [comment]
Its outside of this board but management board will send notification about loss of one of supplies using snmp.
