### ISSUE TITLE
add SPI upgrade connector 

### ISSUE THREAD

**Issue by gkasprow** [elhep/SPEC_A7_Management#8]
add yet another connector for FPGA SPI upgrade
connect FPGA DONE, INIT and UP EN to GPIOs

![obraz](https://github.com/elhep/SPEC_A7_Management/assets/4325054/27877113-f830-4bf2-ac51-0b04bbcf3d23)
![obraz](https://github.com/elhep/SPEC_A7_Management/assets/4325054/6cbe76e1-a27b-4f1b-a16b-099e33a1615d)

**Comment by gyorka** [comment]
we need SAMTEC_ESQ-104-12-L-D for this, using "compatible" connector right now, CERN library needs to be updated
